window.KIYMIK_EPISODES = [
  {
    "number": 1,
    "title": "KAYBOLAN RÖPORTAJ",
    "content": "Öykü'nün ödevi bir mesleği tanıtmak için o meslek çalışanıyla röportaj yapmaktır. Ödevini derste sunacaktır. Sorularını hazırlar. Baba mesleğini sürdüren marangoz olan dedesiyle ahşap tamir atölyesinde otururlar. Öykü ses kayıt cihazını çalıştırıp tezgâhın üzerine koyar, sırayla sorularını sormaya başlar. Dede, mesleğini seçmeye kaç yaşındayken karar verdiğini, babası çalışırken marangozhanede nasıl oynadığını anlatır. Arada Öykü’ye ses kayıt cihazını göstererek “Çalışıyor mu?” diye sorar. Öykü kendinden emin “Çalışıyor dedem, sen merak etme,” der. Neden bu mesleği seçtiğini, işine özel giydiği kıyafeti, kullandığı araç gereçleri, işinin eğlenceli ve zor yanlarını, kimlere hizmet verdiğini, çalışırken zorlanıp zorlanmadığını bir bir anlatır. Dede hangi aletlerin babasından kaldığını gösterir, anılarını anlatır. Öykü, dedesine röportaj için teşekkür eder. Kayıt cihazını kapatmak için eline alır. Bir çığlık atar. Cihazın düğmesi yanmıyordur. Kayıt yapmamıştır. Dede ile bütün konuştukları boşa gitmiştir ancak Öykü’nün elinde sorular vardır. Dersin başlamasına az zaman kalmıştır. Neler yapabileceğini düşünür ve bir yol bulur Öykü. Dedesine onunla birlikte sınıfına gelmesini teklif eder. Bunun öğretmenini ve arkadaşlarını daha çok mutlu edeceğini söyler. Dede okula gelmeyi, röportajın aynısını okulda yapmayı kabul eder. Dede “Ödevini son dakikaya bırakmasaydın ses kayıt cihazını tamir edebilirdim ama şimdi benim elimi kolumu bağladın.” der. Öykü makası alıp gelir, dedenin elini kolunu yoklayıp görünmez ipleri arar. Dede ne yaptığını sorduğunda, “Elin kolun bağlıyken okula nasıl gideceksin, ipleri bulmaya çalışıyorum bana biraz yardımcı olur musun dedem?” der. Dede aletlerinden bazılarını da okula götürmek ister. Öykü annesinden ailenin seyahat valizini ister, onun içine aletleri doldururlar. Dede çocuklar sınıfta oynasın diye Öykü’den saklı, sürpriz ahşap satranç takımı yapmıştır. Dede “Sınıfınıza misafir olacağıma göre, misafir eli boş gitmez,” diyerek satranç takımını da okula götürmek üzere valizin içine koyarlar. Öykü hem sürpriz için hem de dedesiyle sınıfında bir etkinlik yapacağı için çok mutludur."
  },
  {
    "number": 2,
    "title": "TASARRUF DEDEKTİFLERİ İŞ BAŞINDA",
    "content": "Eski usul evlerde olduğu gibi Kıymık Ailesi’nin de bütün oda kapıları, evin merkezindeki salona açılır. Hafta sonudur. Dev çöp poşeti salonun ortasında durmaktadır. Herkes poşetle odası arasında mekik dokuyarak çöplerini, atılacaklarını, odasında gereksiz ne varsa poşete taşır. Arda, küçülen kurşunkalemlerini poşete atmak üzereyken dede onu durdurur. Kalemleri ister, Arda dedesine küçülmüş kurşunkalemlerini verir. Dede marangozhanesinde torunlarına sürpriz, küçülen kalemleri rahatça tutabilecekleri ve minicik kalana dek kullanmalarını sağlayacak kalem uzatıcı yapacaktır. Baba eskimiş oduncu gömleklerini poşete atacakken anne onları kenara ayırır. Bu gömleklerden Öykü’ye oyuncak kedi, Arda’ya gömlek dikecektir, bir de toz bezi. Dede, odasından çıkardığı kucak dolusu pet şişeleri poşete atmak üzereyken Öykü yetişir, şişeleri alır. Bunların çöp değil geri dönüştürülebilen atık olduğunu söyler. Her atık için çöp poşetinin yanına ayrı atık poşetleri konur. Odalardan çıkan atık malzemeler bu poşetlere atılır. Öykü’nün yine harika bir fikri vardır: Yağmur suları da işe yaramalıdır. Dede çocuklarla birlikte tasarlayıp ürettiği bir mekanizmayı bahçedeki su oluklarına monte eder. Böylece yağmur suları bahçedeki ağaçları, çiçekleri sular. Arda dünden kalan yemeği yemek istemez. Bu sorunu çözmek de yine Öykü’ye kalır. Elektriğin, suyun, kâğıt ürünlerinin, sabunun vs. tasarruflu kullanımını işleyen bölümde verilmek istenen mesaj: evimizdeki ekonomik tutumlarımız kendi bütçemize katkı olduğu gibi aynı zamanda ülke ekonomisine de katkıdır."
  },
  {
    "number": 3,
    "title": "UNUTULAN ŞİFRE",
    "content": "Salonun ortasında dedenin kendi babasından kalan, şifresi unutulmuş ağır bir ahşap sandık durur. Aile bireyleri sandığın içinde ne olduğunu tahmin etmeye çalışır. Öykü ve Arda sandığın içinde büyük bir hazine olduğunu düşünerek heyecanla açmaya çalışırlar. Sandığı açmak kolay değildir. Sırayla herkes şansını dener. Baba matematiksel kombinasyonların işe yarayacağını düşünür, doğum tarihleri, telefon numaraları, yıldönümleri... Anne her anahtar değiştirişinde şangır şungur sesler çıkararak anahtar koleksiyonunu kullanır. Arda sandıkla tatlı dille konuşarak ikna yoluna gider. Ne de olsa tatlı dil yılanı deliğinden çıkarır. Öykü bir yılanla karşılaşmak istemediği için çığlığı basar. Sandığın açılmasına karşı çıkar. Atasözünün açıklanmasından sonra ikna olur. Öykü kilidi ve sandığı pek çok açıdan büyüteciyle inceler. Tozlu sandığa her dokunduklarında kalkan toz bulutu, hepsini hapşırma krizine sokar. Komik hapşırma hallerine, yüz ifadelerine tanık olunur. Sandığı açmadan önce temizlemeye karar verirler. Sildikçe üzerindeki nefis işlemeler, kabartmalar ortaya çıkar. Öykü büyüteciyle tüm aileye lüle taşından objeleri, Porsuk nehrinde yüzen sandalları, oltalarını Porsuk nehrine atmış balıkçıları, (Midas Anıtı) Yazılıkaya Anıtı’nı, Odunpazarı evlerini gösterir.  Dede sandığın şifresinin bir rakam değil, aileye dair unutulmuş ortak bir hatıra olduğunu hatırlar. Öykü sandık üzerindeki tüm işlemelerin Eskişehir’e ait olduğuna dikkati çeker. Bunun üzerine dedenin aklına gelir: Babasının marangozhanesini kurup ailesini büyüttüğü şehrin il plaka kodudur şifre. Sandık sonunda açıldığında içinden hazine değil, ailenin yıllar önce çekilmiş fotoğrafları çıkar. En çok ilgiyi dedenin çocukluk fotoğrafları çeker. Arda bir fotoğrafı kendisinin zanneder, şaşırır, dedesine o kadar benzemektedir. İki kardeş, en büyük hazinenin aileyle bir arada bulunmak olduğunu anlar."
  },
  {
    "number": 4,
    "title": "ÇOCUK DEDEMiZ",
    "content": "Öykü ve Arda, aileye sürpriz yapmak için dedelerinin çocukluk fotoğraflarını yazıcıdan taratarak bilgisayara yüklerler. Fotoğraflardan kısa film çekerler. Filmi aileye izletmeden önce kendileri izlerler. Cemal Dede’nin çocukluğuna tanıklık ederken o zamanla kendi yaşadıkları dönem arasındaki farkları görürler. Bir ara elektrikler gider, bilgisayardan cazırtılar, cuzurtular ve adeta gözleri kör eden ışıklar çıkar, iki kardeş kendilerini 1968 yılında, boş bir arsada top oynayan çocukların yanında bulurlar. Dede henüz sekiz yaşında bir çocuktur. Birden yanında beliren Arda ve Öykü’yü oyuna davet eder. Birlikte top oynarlar. Yorulduktan sonra mahalle bakkalından çocuk dedenin yeni arkadaşları Öykü ve Arda’ya ısmarladığı Çamlıca Gazozunu, duvarın üzerine oturup içerler. Cemal heyecanla televizyon seyredip seyretmediklerini sorar. Babası eve ilk televizyonlarını almıştır. Arda “Biz her gün biraz izliyoruz, asıl cep telefonu…” diyecekken Öykü onu dürter. Çocuk dedenin gözleri kocaman açılır. “Uydurmayın haftada üç gün üçer saat yayın yapılıyor. Siz nasıl her gün televizyon seyredersiniz?” diyerek karşı çıkar. “Bugün salı, yayın günü. 19.30’da başlayacak, kaçırmayalım.” diyerek Arda ile Öykü’yü evine davet eder. Anne babasıyla tanıştırır. Tüm aile ve misafirler televizyonun karşısında yan yana divana sıkışır. Tüplü televizyon Öykü ve Arda’ya çok ilginç gelir. Baba televizyonun üzerindeki danteli alır ve açma düğmesine basar. Karlı görüntünün ardından ekranda spiker belirir. Herkes alkışlar. Siyah beyaz görüntü karşısında iki kardeşin ağzı açık kalır. Herkes onları televizyona şaşırdılar sanır. Öykü masanın üzerindeki mumların neden orada olduğunu sorar. “Elektrik kesintileri yüzünden.” der çocuk dede. O sırada elektrik kesilir. Öykü ile Arda kendilerini şimdiki zamanda salonlarında bulurlar. Akşam dedelerinin iki yanına oturup ona sarılarak onun için hazırladıkları filmi aileye gösterirler. Dede çok duygulanır ve onurlanır. “Benim çocukluğumda siyah beyaz tüplü televizyon vardı.” diyen dedeye çocuklar gülümserler, birbirlerine fısıldar, göz kırparlar: “Biliyoruz.”"
  },
  {
    "number": 5,
    "title": "PİKNİK NEREDE YAPILIR?",
    "content": "Dedeyle pikniğe gitmeye karar veren çocuklar aniden bastıran yağmur ve ardından kesilen elektrikle çok üzülürler. Çocukların moralini düzeltmek isteyen dede, piknik alanını salonun ortasına kurmaya karar verir. Salondaki koltuk minderleri, yastıklar, yemek masası, kendi odasından getirdiği pikeyle bir çadır kurar. Çocuklar çadırı çok severler. Fenerlerle gölge oyunları oynar, el feneri ışığında bisküvi köfteleri pişirirler. Pikniğe küçük bir ara verirler. Dede ışığı pır pır yapan fener için atölyeden pil almaya, Arda tuvalete, Öykü’de annesinin diktiği kareli kediyi pikniklerine dahil etmek için odasından almaya gider. Bu sırada piknikçilerden habersiz salona giren baba dehşete kapılır, eşi işten döndüğünde evi dağınık bulmasın diye hemen her yeri toplar, düzenler, her şeyi yerleştirir, salondan huzurlu ve mutlu şekilde çıkar. Aynı anda salonda buluşan piknikçiler dede, Öykü ve Arda gözlerine inanamazlar. Az önce buraya kurdukları çadır nereye gitmiştir? Bu defa işin içine çarşafların da girdiği öncekinden büyük bir çadır kurarlar. Pikniklerine devam ederlerken anne yorgun argın işten eve gelir. Hava kararmak üzeredir. Elektrikler hâlâ gelmemiştir. Anne de çadır eğlencesine sevinçle katılır. Baba elinde mumla girip az önce derli toplu bıraktığı salondaki çadırı görünce çok şaşırır. Baba için asıl sürpriz çadırın içinde eşinin de olmasıdır. İçinde buz parçaları yüzen leğene ayaklarını sokup telefondan deniz dalgalarının sesi dinlemek, anneyi çok dinlendirir. Tüm aile gerçek doğada olmasalar da birbirlerinin varlığıyla elektriksiz ve yağmurlu bir günün halının üzerinde unutulmaz bir piknik anısına dönüşebildiğini görür."
  },
  {
    "number": 6,
    "title": "AİLENİN YENİ ÜYESİ",
    "content": "Sonunda hayvanları çok seven Öykü’nün en büyük dileği gerçek olur: Kıymık Ailesi sokaktan bir kedi sahiplenir. Çocuklar sarı tekirin adını Zımpara koyarlar. Çocuklar neredeyse Zımpara’da oradadır. Gündüz atölyede, akşamları da evde hep birlikte zaman geçirirler. Çocuklar ödev yaparken kitapların üzerinde uyur, silgileri, kelemleriyle oynar, küçük okul eşyalarını kendine oyuncak yapan Zımpara, dedeyi de ihmal etmez. Onun aletlerini patiler, ağzında taşıyabildiklerini kaçırır, olmadık yerlere saklar. Dede aradığı aleti koyduğu yerde bir türlü bulamaz. Arda’nın gözleri hiç olmadığı kadar kaşınır. Artık hep kızarmış gözlerini kaşıyarak ödevlerini yapar, atölyedeki işlere yardımcı olur. Sadece okuldayken kaşıntı ve kızarıklıkları yoktur. Öykü’nün durumu daha kötüdür. Öykü hapşırmaya başladığı zaman Arda’da saymaya başlar: Bir, iki, üç… dokuz, on, on bir… Öykü’nün sonu gelmez hapşırık nöbetleri ve burun akıntıları, Arda’nın kaşıntı ve kızarıklıkları ailenin dikkatini çeker, çocukları doktora götürürler. İki çocuk da eve beş karış suratla döner. “Biz şikayetçi değiliz, böyle idare edebiliriz, yeter ki Zımpara’dan ayrılmayalım.” derler. Alerji ilaçları çocukların sıkıntılarını biraz yatıştırsa da sorun devam etmektedir. Sonunda Öykü’nün aklına bir çözüm gelir. Hayalindeki kedi evini çizer. Dedesi ve Arda’yla birlikte arka bahçeye Zımpara ve arkadaşları için iki katlı beş gözlü çok şık ve kullanışlı bir ahşap kedi evi yaparlar. Rengarenk boyayıp üzerine pati görselleri çizerler. İçine yumuşacık minderler yerleştirirler. Hem bahçede olmak hem de çocuklardan ayrılmamak Zımpara’yı çok mutlu eder. Çocuklar da istediklerinde kedileriyle zaman geçirir, her gün onun tüm ihtiyaçlarını karşılarlar. Bir canlıyı yuvaya kavuşturmanın ve onun sorumluluğunu almanın mutluluğunu yaşarlar."
  },
  {
    "number": 7,
    "title": "EMEKTAR TEZGÂHA NE OLACAK?",
    "content": "Atölyenin ortasında duran, dedenin babasından miras dev asırlık meşe çalışma tezgâhı zamana yenik düşer, ortasında derin bir çatlak oluşur. Kıymık Ailesi üyelerinin her biri çatlağın giderilmesi konusunda farklı bir çözüm yolu önerir. Uzlaşamazlar, tartışma büyür: Baba, eski tezgâhı atıp yerine yeni tezgâh almayı önerir. Dede, babasından kalma tezgâha gönül bağıyla bağlıdır, üzerini metalle kaplamayı teklif eder. Arda ve Öykü zamanlarının büyük kısmını atölyede geçirdikleri için anne güvenlik gerekçesiyle çatlak tezgâhın atölyeden çıkarılmasını ister. Çatışma, ailenin merkezindeki değerin nasıl korunacağı krizine dönüşür. Aile ilk kez büyük bir fikir ayrılığına düşer. Çözüm yine Öykü’den gelir. Japon porselen birleştirme sanatı Kintsugi’yi daha önce belgeselde izleyip ilginç bulan Öykü bunun nasıl bir teknik olduğunu ailesine anlatır. Bu tekniği ahşaba nasıl uyarlayacaklarını düşünürler. Dede bunun marangozlukta kullanılan bir yöntem olduğunu, kırlangıç kuyruğu birleştirme yönteminin Kintsugi’ye karşılık gelebileceğini belirtir. Çatlağı gizlemek veya tezgâhı atmak yerine, ailece birlikte çalışarak çatlağı daha sağlam ve koyu renkli bir ceviz ahşap kamayla doldururlar. Çatlak kapanır tezgâh eskisinden daha güçlü ve estetik hale gelir. Aile, kusurların ve krizlerin birleşerek aşıldığında bağları güçlendirdiğini deneyimler."
  },
  {
    "number": 8,
    "title": "SATIŞ KAHRAMANI",
    "content": "Kıymık ​Ailesi, fazla eşyaları elden çıkarmak ve mahalleden bir ihtiyaç sahibine destek olmak için bahçelerinde satış düzenler. Pazar günü satılacak tüm eşyaları bahçeye çıkarır, komşuları davet ederler. Ancak Öykü, oyuncakları ve küçülen bebeklik eşyaları satılırken her birine aniden aşırı bir duygusal bağ geliştirir. Onları geri satın almak için kumbarasındaki bozuk paraları çıkarmaya çalışır. Durumu fark eden Arda, anne, baba, dede, Öykü’ye eşyaların kendisinin değil, o eşyalarla yaşanan güzel anıların değerli olduğunu anlatan eğlenceli bir \"hatıra draması\" oyunu oynarlar. Öykü, eşyaları başka bir küçük çocuğun yüzünü güldürürken gördüğünde, paylaşmanın bir şeyleri kaybetmek olmadığını anlar."
  },
  {
    "number": 9,
    "title": "YENİLMEZ YEŞİL EJDERHA’NIN ARKADAŞI",
    "content": "Arda yetenekli olduğu resim dersini çok sever. Resim çizerken kendini adeta ressam gibi hisseder.  Şövalesini kurar haftalarca yeşilin çeşitli tonlarını elde ederek Yenilmez Yeşil Ejderha adını verdiği tablosu üzerinde çalışır. Okul sergisi için hazırladığı bu resme çok özenir. Gerçekten ortaya çok güzel bir resim çıkar. Sergiden bir gece önce Öykü, ejderhanın yanına pembe bir fil resmi çizer. Üstelik bunu Arda’ya bir sevgi göstergesi olarak “Ejderhana arkadaş yaptım.” diyerek gururla sunar. Pembe filden sonra ortalık biraz karışır. Arda \"Vay canına, ejderham tam da pembe bir fil dost arıyordu...\" diyebilecek mi, yoksa zaman makinesinin icat edilmiş olmasını mı isteyecek? Geri döndürülemez olaylara soğukkanlı ve biraz da mizahla yaklaşmalı. Dedenin bir anısı Arda’yı teselli etmeye yetecek mi? İyi niyetli yapılan hatalar hoşgörüyle karşılansa belki de kötünün içindeki iyiyi görürüz."
  },
  {
    "number": 10,
    "title": "KURABİYE AVI",
    "content": "Anne, akşam gelecek misafirler için hazırladığı efsanevi çikolatalı kurabiyeleri, çocuklardan korumak için yüksek bir dolaba kaldırıp üzerini mutfak kronometresi ve zil mekanizmasıyla \"tuzaklamıştır\". Çocuklar, kurabiyeleri ele geçirmek için adeta soygun filminde gibi hareket ederler. Babanın gazete okurken çıkardığı seslerden zamanlama ayarlar, annelerinin hareketlerini gözlemler, dedeyi atlatırlar. Ancak tam kurabiyeye ulaşacakken, aslında annenin tüm bu tuzakları onların zekâsını ve iş birliğini test etmek için kurduğu ve en üst rafa kurabiye yerine \"Başardınız, kutlarım.\" notu bıraktığı ortaya çıkar. Kurabiyeler fırında sıcak bir şekilde beklemektedir."
  },
  {
    "number": 11,
    "title": "“ÇOK GİZLİ” BAHÇE SIĞINAĞI",
    "content": "Arda, bahçedeki yaşlı kiraz ağacının arkasına, çalı ayıklama makinesinden çıkan dallarla kendisi için küçücük bir sığınak oluşturmuştur. Burası onun resim çizdiği, kendi kendine konuştuğu, kimsenin girmediği özel alanıdır. Girişine de kâğıttan bir “ARDA’NIN BÖLGESİ – GİRİLMEZ” tabelası asmıştır.\n​Bir gün Öykü, abisiyle oyun oynamak ister. Arda'nın “Burası benim özel alanım, şu an yalnız kalmak istiyorum.” demesini anlamaz. Küçük kardeş olmanın verdiği \"her yer benimdir\" özgüveniyle, Arda mutfakta annesine yardım ederken sığınağa dalar. Arda'nın gizli resim defterini çıkarır, sayfalara rengârenk kalpler çizer, Arda’yı ne kadar çok sevdiğini belirten kısa yazılar yazar. Sığınağın dallarını kendince düzenler, “Arda bak, sığınağını güzelleştirdim.” diye bağırır.\n​Arda sığınağını ve dağıtılmış defterini görünce çıldırmaz ya da bağırmaz; sadece gözleri dolar, defterini alıp odasına çekilir, kapısını kapatır. Evde derin bir sessizlik başlar. Öykü, abisinin neden öfkelenmek yerine bu kadar üzüldüğünü anlayamaz. Baba, Öykü’yü yanına oturtup onunla bu olay hakkında konuşur. \"Öykücüğüm, herkesin bazen kendi düşünceleriyle baş başa kalacağı gizli bir bahçeye ihtiyacı vardır. Sen onun sığınağına girdiğinde, onun zihnindeki o sakin odayı dağıtmış oldun.\"\n​Öykü hatasını anlar, durumu telafi etmek için plan yapar: Mutfaktaki annesinden yardım alıp minik bir özür kurabiyesi pişirir. Sonra Arda’nın kapısına gider, içeri girmeden, kurabiyeyi kapının önüne bırakır ve bir adım geri çekilip bekler. Arda odasından çıkıp kurabiyeyi ve Öykü’nün çizdiği “özür dilerim” yazısını ve Arda için yaptığı resmi görünce gülümser. İki kardeş, birbirlerinin özel alanlarına saygı duymanın, aslında birbirini sevmenin en zekice yolu olduğunu keşfederler. Öykü, birini gerçekten sevmenin, onun sınırlarına saygı duymaktan geçtiğini anlar."
  },
  {
    "number": 12,
    "title": "SABIR KUTUSUNUN İÇİNDE NE VAR?",
    "content": "Öykü ve Arda en yakın arkadaşlarını bahçede birlikte oynamak için çağırmışlardır. Altı çocuk birlikte keyifli vakit geçirmeye başlarlar. Ne zaman Arda ebe olsa ebeliği geçer geçmez “Ben çok sıkıldım, oyun değiştirelim.” der. Birkaç defa oyun değiştirilip bazı çocuklar hiç ebe olamayınca tartışma çıkar. Arda sabırsızlıkla ve başkalarının haklarına saygı duymamakla suçlanır. Arda odasına çekilir biraz telefonuyla oynar ama aklı bahçede çok eğlenen, kahkahalarını duyduğu arkadaşlarında kalmıştır. Gün biter konuk çocuklar evlerine giderler. Durumu atölyesinin penceresinden gözlemleyen dede, sofrada suratı asık Arda’yla konuşmaya çalışır ama Arda hatasını kabul etmek istemez. Bunun üzerine anne herkesi bir hafta sürecek bir oyuna davet eder. Bu oyunda herkes hafta boyunca ebedir. İçlerinde ne olduğunu sadece dedenin bildiği küçük kutular aile bireylerine rastgele dağıtılacaktır. Oyunda iki kural vardır. Birincisi, herkes hafta boyunca kutusunu yanında taşıyacak, gittiği her yere götürecektir. İkincisi hafta sonuna, oyun bitene dek kutular açılmayacak, hafta sonu tüm aile bir araya gelip sabır kutularını açıp nihayet içindekini öğrenecektir. Arda, zorlayıcı olacak bu oyunu oynayabilecek, kutusunu açmadan, ebeliğini yakmadan haftayı tamamlamayı başarabilecek midir?"
  }
];
